export const SERVER_LIST_REQUEST = "SERVER_LIST_REQUEST";
export const SERVER_LIST_SUCCESS = "SERVER_LIST_SUCCESS";
export const SERVER_LIST_FAIL = "SERVER_LIST_FAIL";

export const SERVER_DETAILS_REQUEST = "SERVER_DETAILS_REQUEST";
export const SERVER_DETAILS_SUCCESS = "SERVER_DETAILS_SUCCESS";
export const SERVER_DETAILS_FAIL = "SERVER_DETAILS_FAIL";

export const SERVER_ON_REQUEST = "SERVER_ON_REQUEST";
export const SERVER_ON_SUCCESS = "SERVER_ON_SUCCESS";
export const SERVER_ON_FAIL = "SERVER_ON_FAIL";

export const SERVER_OFF_REQUEST = "SERVER_OFF_REQUEST";
export const SERVER_OFF_SUCCESS = "SERVER_OFF_SUCCESS";
export const SERVER_OFF_FAIL = "SERVER_OFF_FAIL";

export const SERVER_REBOOT_REQUEST = "SERVER_REBOOT_REQUEST";
export const SERVER_REBOOT_SUCCESS = "SERVER_REBOOT_SUCCESS";
export const SERVER_REBOOT_FAIL = "SERVER_REBOOT_FAIL";

